/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuporteRedefinir2faRouteImport } from './routes/suporte.redefinir-2fa'
import { Route as EmpresaIdRouteImport } from './routes/empresa.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AuthTwoFactorRouteImport } from './routes/auth_.two-factor'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedCadastrarEmpresaRouteImport } from './routes/_authenticated/cadastrar-empresa'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedOwnerIndexRouteImport } from './routes/_authenticated/owner.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedPainelSegurancaRouteImport } from './routes/_authenticated/painel.seguranca'
import { Route as AuthenticatedPainelConfiguracoesRouteImport } from './routes/_authenticated/painel.configuracoes'
import { Route as AuthenticatedPainelAvaliacoesRouteImport } from './routes/_authenticated/painel.avaliacoes'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push.dispatch'
import { Route as ApiPublicHooksNotificationEmailRouteImport } from './routes/api/public/hooks/notification-email'
import { Route as AuthenticatedOwnerEmpresaIdProdutosRouteImport } from './routes/_authenticated/owner.empresa.$id.produtos'
import { Route as AuthenticatedOwnerEmpresaIdEditarRouteImport } from './routes/_authenticated/owner.empresa.$id.editar'
import { Route as AuthenticatedOwnerEmpresaIdDashboardRouteImport } from './routes/_authenticated/owner.empresa.$id.dashboard'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRedefinir2faRoute = SuporteRedefinir2faRouteImport.update({
  id: '/suporte/redefinir-2fa',
  path: '/suporte/redefinir-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaIdRoute = EmpresaIdRouteImport.update({
  id: '/empresa/$id',
  path: '/empresa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/auth_/two-factor',
  path: '/auth/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrarEmpresaRoute =
  AuthenticatedCadastrarEmpresaRouteImport.update({
    id: '/cadastrar-empresa',
    path: '/cadastrar-empresa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedOwnerIndexRoute = AuthenticatedOwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelSegurancaRoute =
  AuthenticatedPainelSegurancaRouteImport.update({
    id: '/seguranca',
    path: '/seguranca',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelConfiguracoesRoute =
  AuthenticatedPainelConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAvaliacoesRoute =
  AuthenticatedPainelAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push/dispatch',
  path: '/api/public/push/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNotificationEmailRoute =
  ApiPublicHooksNotificationEmailRouteImport.update({
    id: '/api/public/hooks/notification-email',
    path: '/api/public/hooks/notification-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOwnerEmpresaIdProdutosRoute =
  AuthenticatedOwnerEmpresaIdProdutosRouteImport.update({
    id: '/owner/empresa/$id/produtos',
    path: '/owner/empresa/$id/produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerEmpresaIdEditarRoute =
  AuthenticatedOwnerEmpresaIdEditarRouteImport.update({
    id: '/owner/empresa/$id/editar',
    path: '/owner/empresa/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerEmpresaIdDashboardRoute =
  AuthenticatedOwnerEmpresaIdDashboardRouteImport.update({
    id: '/owner/empresa/$id/dashboard',
    path: '/owner/empresa/$id/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/contato': typeof ContatoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cadastrar-empresa': typeof AuthenticatedCadastrarEmpresaRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/suporte/redefinir-2fa': typeof SuporteRedefinir2faRoute
  '/painel/avaliacoes': typeof AuthenticatedPainelAvaliacoesRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/seguranca': typeof AuthenticatedPainelSegurancaRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/owner/': typeof AuthenticatedOwnerIndexRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/api/public/hooks/notification-email': typeof ApiPublicHooksNotificationEmailRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/owner/empresa/$id/dashboard': typeof AuthenticatedOwnerEmpresaIdDashboardRoute
  '/owner/empresa/$id/editar': typeof AuthenticatedOwnerEmpresaIdEditarRoute
  '/owner/empresa/$id/produtos': typeof AuthenticatedOwnerEmpresaIdProdutosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/contato': typeof ContatoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cadastrar-empresa': typeof AuthenticatedCadastrarEmpresaRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/suporte/redefinir-2fa': typeof SuporteRedefinir2faRoute
  '/painel/avaliacoes': typeof AuthenticatedPainelAvaliacoesRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/seguranca': typeof AuthenticatedPainelSegurancaRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/owner': typeof AuthenticatedOwnerIndexRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/api/public/hooks/notification-email': typeof ApiPublicHooksNotificationEmailRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/owner/empresa/$id/dashboard': typeof AuthenticatedOwnerEmpresaIdDashboardRoute
  '/owner/empresa/$id/editar': typeof AuthenticatedOwnerEmpresaIdEditarRoute
  '/owner/empresa/$id/produtos': typeof AuthenticatedOwnerEmpresaIdProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/contato': typeof ContatoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/cadastrar-empresa': typeof AuthenticatedCadastrarEmpresaRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/auth_/two-factor': typeof AuthTwoFactorRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/suporte/redefinir-2fa': typeof SuporteRedefinir2faRoute
  '/_authenticated/painel/avaliacoes': typeof AuthenticatedPainelAvaliacoesRoute
  '/_authenticated/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/_authenticated/painel/seguranca': typeof AuthenticatedPainelSegurancaRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/owner/': typeof AuthenticatedOwnerIndexRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/api/public/hooks/notification-email': typeof ApiPublicHooksNotificationEmailRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/owner/empresa/$id/dashboard': typeof AuthenticatedOwnerEmpresaIdDashboardRoute
  '/_authenticated/owner/empresa/$id/editar': typeof AuthenticatedOwnerEmpresaIdEditarRoute
  '/_authenticated/owner/empresa/$id/produtos': typeof AuthenticatedOwnerEmpresaIdProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buscar'
    | '/contato'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin'
    | '/cadastrar-empresa'
    | '/favoritos'
    | '/notificacoes'
    | '/painel'
    | '/auth/two-factor'
    | '/categoria/$slug'
    | '/email/unsubscribe'
    | '/empresa/$id'
    | '/suporte/redefinir-2fa'
    | '/painel/avaliacoes'
    | '/painel/configuracoes'
    | '/painel/seguranca'
    | '/lovable/email/suppression'
    | '/owner/'
    | '/painel/'
    | '/api/public/hooks/notification-email'
    | '/api/public/push/dispatch'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/owner/empresa/$id/dashboard'
    | '/owner/empresa/$id/editar'
    | '/owner/empresa/$id/produtos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buscar'
    | '/contato'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin'
    | '/cadastrar-empresa'
    | '/favoritos'
    | '/notificacoes'
    | '/auth/two-factor'
    | '/categoria/$slug'
    | '/email/unsubscribe'
    | '/empresa/$id'
    | '/suporte/redefinir-2fa'
    | '/painel/avaliacoes'
    | '/painel/configuracoes'
    | '/painel/seguranca'
    | '/lovable/email/suppression'
    | '/owner'
    | '/painel'
    | '/api/public/hooks/notification-email'
    | '/api/public/push/dispatch'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/owner/empresa/$id/dashboard'
    | '/owner/empresa/$id/editar'
    | '/owner/empresa/$id/produtos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/buscar'
    | '/contato'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sobre'
    | '/_authenticated/admin'
    | '/_authenticated/cadastrar-empresa'
    | '/_authenticated/favoritos'
    | '/_authenticated/notificacoes'
    | '/_authenticated/painel'
    | '/auth_/two-factor'
    | '/categoria/$slug'
    | '/email/unsubscribe'
    | '/empresa/$id'
    | '/suporte/redefinir-2fa'
    | '/_authenticated/painel/avaliacoes'
    | '/_authenticated/painel/configuracoes'
    | '/_authenticated/painel/seguranca'
    | '/lovable/email/suppression'
    | '/_authenticated/owner/'
    | '/_authenticated/painel/'
    | '/api/public/hooks/notification-email'
    | '/api/public/push/dispatch'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/owner/empresa/$id/dashboard'
    | '/_authenticated/owner/empresa/$id/editar'
    | '/_authenticated/owner/empresa/$id/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  ContatoRoute: typeof ContatoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  EmpresaIdRoute: typeof EmpresaIdRoute
  SuporteRedefinir2faRoute: typeof SuporteRedefinir2faRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksNotificationEmailRoute: typeof ApiPublicHooksNotificationEmailRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte/redefinir-2fa': {
      id: '/suporte/redefinir-2fa'
      path: '/suporte/redefinir-2fa'
      fullPath: '/suporte/redefinir-2fa'
      preLoaderRoute: typeof SuporteRedefinir2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/$id': {
      id: '/empresa/$id'
      path: '/empresa/$id'
      fullPath: '/empresa/$id'
      preLoaderRoute: typeof EmpresaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/two-factor': {
      id: '/auth_/two-factor'
      path: '/auth/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastrar-empresa': {
      id: '/_authenticated/cadastrar-empresa'
      path: '/cadastrar-empresa'
      fullPath: '/cadastrar-empresa'
      preLoaderRoute: typeof AuthenticatedCadastrarEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/owner/': {
      id: '/_authenticated/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof AuthenticatedOwnerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/seguranca': {
      id: '/_authenticated/painel/seguranca'
      path: '/seguranca'
      fullPath: '/painel/seguranca'
      preLoaderRoute: typeof AuthenticatedPainelSegurancaRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/configuracoes': {
      id: '/_authenticated/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof AuthenticatedPainelConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/avaliacoes': {
      id: '/_authenticated/painel/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/painel/avaliacoes'
      preLoaderRoute: typeof AuthenticatedPainelAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/dispatch': {
      id: '/api/public/push/dispatch'
      path: '/api/public/push/dispatch'
      fullPath: '/api/public/push/dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notification-email': {
      id: '/api/public/hooks/notification-email'
      path: '/api/public/hooks/notification-email'
      fullPath: '/api/public/hooks/notification-email'
      preLoaderRoute: typeof ApiPublicHooksNotificationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/owner/empresa/$id/produtos': {
      id: '/_authenticated/owner/empresa/$id/produtos'
      path: '/owner/empresa/$id/produtos'
      fullPath: '/owner/empresa/$id/produtos'
      preLoaderRoute: typeof AuthenticatedOwnerEmpresaIdProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/empresa/$id/editar': {
      id: '/_authenticated/owner/empresa/$id/editar'
      path: '/owner/empresa/$id/editar'
      fullPath: '/owner/empresa/$id/editar'
      preLoaderRoute: typeof AuthenticatedOwnerEmpresaIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/empresa/$id/dashboard': {
      id: '/_authenticated/owner/empresa/$id/dashboard'
      path: '/owner/empresa/$id/dashboard'
      fullPath: '/owner/empresa/$id/dashboard'
      preLoaderRoute: typeof AuthenticatedOwnerEmpresaIdDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelAvaliacoesRoute: typeof AuthenticatedPainelAvaliacoesRoute
  AuthenticatedPainelConfiguracoesRoute: typeof AuthenticatedPainelConfiguracoesRoute
  AuthenticatedPainelSegurancaRoute: typeof AuthenticatedPainelSegurancaRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelAvaliacoesRoute: AuthenticatedPainelAvaliacoesRoute,
  AuthenticatedPainelConfiguracoesRoute: AuthenticatedPainelConfiguracoesRoute,
  AuthenticatedPainelSegurancaRoute: AuthenticatedPainelSegurancaRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCadastrarEmpresaRoute: typeof AuthenticatedCadastrarEmpresaRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
  AuthenticatedOwnerIndexRoute: typeof AuthenticatedOwnerIndexRoute
  AuthenticatedOwnerEmpresaIdDashboardRoute: typeof AuthenticatedOwnerEmpresaIdDashboardRoute
  AuthenticatedOwnerEmpresaIdEditarRoute: typeof AuthenticatedOwnerEmpresaIdEditarRoute
  AuthenticatedOwnerEmpresaIdProdutosRoute: typeof AuthenticatedOwnerEmpresaIdProdutosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCadastrarEmpresaRoute: AuthenticatedCadastrarEmpresaRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
  AuthenticatedOwnerIndexRoute: AuthenticatedOwnerIndexRoute,
  AuthenticatedOwnerEmpresaIdDashboardRoute:
    AuthenticatedOwnerEmpresaIdDashboardRoute,
  AuthenticatedOwnerEmpresaIdEditarRoute:
    AuthenticatedOwnerEmpresaIdEditarRoute,
  AuthenticatedOwnerEmpresaIdProdutosRoute:
    AuthenticatedOwnerEmpresaIdProdutosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  ContatoRoute: ContatoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  EmpresaIdRoute: EmpresaIdRoute,
  SuporteRedefinir2faRoute: SuporteRedefinir2faRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksNotificationEmailRoute: ApiPublicHooksNotificationEmailRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
